# Generated by Django 2.0 on 2018-03-29 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callno', models.CharField(max_length=20)),
                ('accno', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookissue', models.ForeignKey(on_delete=False, to='Libr.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('RollNo', models.CharField(max_length=6)),
                ('Branch', models.CharField(max_length=10)),
                ('Pic', models.FileField(upload_to='docs/')),
                ('username', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='stud',
            field=models.ForeignKey(on_delete=False, to='Libr.Student'),
        ),
    ]
