# Generated by Django 2.0 on 2018-04-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libr', '0002_book_is_available'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('stud', 'bookissue')},
        ),
    ]
