# Generated by Django 2.0 on 2018-04-07 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libr', '0004_auto_20180407_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_date',
            field=models.DateField(default=datetime.date(2018, 4, 7)),
        ),
    ]
