# Generated by Django 2.0 on 2018-04-07 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libr', '0005_issue_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='due_date',
            field=models.DateField(default=datetime.date(2018, 5, 7)),
        ),
        migrations.AddField(
            model_name='student',
            name='Fine',
            field=models.FloatField(default=0),
        ),
    ]
