# Generated by Django 2.0 on 2018-04-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libr', '0006_auto_20180407_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='NoofBooks',
            field=models.IntegerField(default=0),
        ),
    ]
