# Generated by Django 2.0 on 2018-04-07 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libr', '0007_student_noofbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='contributer',
            field=models.CharField(default='Authority', max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='due_date',
            field=models.DateField(default=datetime.date(2018, 5, 8)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_date',
            field=models.DateField(default=datetime.date(2018, 4, 8)),
        ),
    ]
